#!/bin/sh

set -e

KK_HOST=${KK_HOST:-keycloak}
KK_PORT=${KK_PORT:-8080}
KK_REALM=${KK_REALM:-external}

REALM_DATA=$(curl -s -m3 "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")

TARGET=${TARGET:-var/secret}

echo "-----BEGIN PUBLIC KEY-----" >> ${TARGET}
echo "${REALM_DATA}" | \
    grep -Po '"public_key":.*?[^\\]",' | \
    sed -e 's/public_key//' -e 's/[":,]//g' | \
    fold -w80 \
    >> ${TARGET}
echo "-----END PUBLIC KEY-----" >> ${TARGET}
