#!/bin/sh

set -e -o pipefail

KK_HOST=${KK_HOST:-keycloak}
KK_PORT=${KK_PORT:-8080}
KK_REALM=${KK_REALM:-external}
TARGET=${TARGET:-var/pubkey.pem}

CURL_OPTS=${CURL_OPTS:-}
MAX_RETRY_TIMEOUT=${MAX_RETRY_TIMEOUT:-10}

TIMEOUT=0

while true; do
    REALM_FAIL=false

    echo "$0: [ INFO ] Attempting to fetch Keycloak key..."

    REALM_DATA=$(curl -s -m5 --fail ${CURL_OPTS} "http://${KK_HOST}:${KK_PORT}/auth/realms/${KK_REALM}")
    EXIT_CODE=$?
    if [ "${EXIT_CODE}" -ne "0" ]; then
        REALM_FAIL=true
        echo "$0: [ ERROR ] Keycloak realm data fetching failed with exit code: ${EXIT_CODE}"
    fi
    if [ -z "${REALM_DATA}" ]; then
        REALM_FAIL=true
        echo "$0: [ ERROR ] Keycloak realm data is empty"
    fi
    if [ "$REALM_FAIL" == false ]; then
        break
    else
        TIMEOUT=$((TIMEOUT + 1))
        TIMEOUT=$([ $TIMEOUT -le $MAX_RETRY_TIMEOUT ] && echo "$TIMEOUT" || echo "$MAX_RETRY_TIMEOUT")
    fi

    echo "$0: [ ERROR ] Keycloak request timeout: ${TIMEOUT}"
    sleep $TIMEOUT
done

echo "$0: [ INFO  ] Keycloak realm data fetched successfully"
echo "$0: [ DEBUG ] ${REALM_DATA}"
echo "$0: [ INFO  ] Writing public key to: ${TARGET} ..."

echo "-----BEGIN PUBLIC KEY-----" > ${TARGET}
echo "${REALM_DATA}" | \
    grep -Po '"public_key":.*?[^\\]",' | \
    sed -e 's/public_key//' -e 's/[":,]//g' | \
    fold -w80 \
    >> ${TARGET}
echo "-----END PUBLIC KEY-----" >> ${TARGET}

echo "$0: [ INFO  ] Everything is ok"
